## NTSC-MAME
default:
  # libretro
  shader: ntsc/mame-ntsc
  # emulators using reshader 
  m2emulator: NTSC_RetroArch@NTSC_RetroArch.fx
  supermodel: NTSC_RetroArch@NTSC_RetroArch.fx
  hypseus: NTSC_RetroArch@NTSC_RetroArch.fx
  daphne: NTSC_RetroArch@NTSC_RetroArch.fx
  oricutron: NTSC_RetroArch@NTSC_RetroArch.fx
  applewin: NTSC_RetroArch@NTSC_RetroArch.fx
  gsplus: NTSC_RetroArch@NTSC_RetroArch.fx
  scummvm: NTSC_RetroArch@NTSC_RetroArch.fx
  simcoupe: NTSC_RetroArch@NTSC_RetroArch.fx
  demul: NTSC_RetroArch@NTSC_RetroArch.fx
  demul-old: NTSC_RetroArch@NTSC_RetroArch.fx
  phoenix: NTSC_RetroArch@NTSC_RetroArch.fx
  bigpemu: NTSC_RetroArch@NTSC_RetroArch.fx
  mednafen: NTSC_RetroArch@NTSC_RetroArch.fx
  solarus: NTSC_RetroArch@NTSC_RetroArch.fx
  redream: NTSC_RetroArch@NTSC_RetroArch.fx
  raine: NTSC_RetroArch@NTSC_RetroArch.fx
