## MEGA BEZEL
default:
  # shader affects retroarch shaders
  shader: crt/crt-geom
  # scanline affect fba2x
  scanline: true
# Reshader  
model2:
  shader: GeomCRT@CRTGeom.fx
model3:
  shader: GeomCRT@CRTGeom.fx
daphne:
  shader: GeomCRT@CRTGeom.fx
solarus:
  shader: GeomCRT@CRTGeom.fx
# Nintendo
snes:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Super_Famicom/Super_Famicom_Alt-[STD]-[Guest]-[Bezel]-[Night]
snes-msu:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Super_Famicom/Super_Famicom_Alt-[STD]-[Guest]-[Bezel]-[Night]
sgb:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Super_Game_Boy/Super_Famicom_SGB-[STD]-[Guest]-[Bezel]-[Night]
nes:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_NES/NES-[STD]-[Guest]-[Bezel]-[Night]
n64:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_N64/N64-[STD]-[Guest]-[Bezel]-[Night]
satellaview:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Super_Famicom/Super_Famicom_Alt-[STD]-[Guest]-[Bezel]-[Night]
sufami:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Super_Famicom/Super_Famicom_Alt-[STD]-[Guest]-[Bezel]-[Night]
gba:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_GBA/GBA-[STD]-[LCD-GRID]-[Night]
gb:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Game_Boy/Gameboy-[STD]-[LCD-GRID]-[Night]
gbc:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Game_Boy_Color/GBC-[STD]-[LCD-GRID]-[Night]
nds:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_NDS/NDS-[STD]-[Guest]
3ds:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_3DS/3DS-[STD]-[Guest]
fds:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Famicom/Famicom-[STD]-[Guest]-[Bezel]-[Night]
virtualboy:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Virtual_Boy/Virtual_Boy-[STD]-[Guest]
gamecube:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Gamecube/Gamecube-[STD]-[Guest]-[Bezel]-[Night]
wii:
  shader: Duimon-Mega-Bezel/Presets/Standard/Nintendo_Wii/Wii_4x3-[Guest-Mini]
# Sega
dreamcast:
  shader: Duimon-Mega-Bezel/Presets/Standard/SEGA_Dreamcast/Dreamcast-[STD]-[Guest]-[Bezel]-[Night]
sg1000:
  shader: Duimon-Mega-Bezel/Presets/Standard/SEGA_SG-1000/SG-1000-[STD]-[Guest]-[Bezel]-[Night]
mastersystem:
  shader: Duimon-Mega-Bezel/Presets/Standard/SEGA_Master_System/SMS-[STD]-[Guest]-[Bezel]-[Night]
megadrive:
  shader: Duimon-Mega-Bezel/Presets/Standard/SEGA_Genesis/Genesis_Alt-[STD]-[Guest]-[Bezel]-[Night]
gamegear:
  shader: Duimon-Mega-Bezel/Presets/Standard/SEGA_Game_Gear/Game_Gear-[STD]-[LCD-GRID]-[Night]
sega32x:
  shader: Duimon-Mega-Bezel/Presets/Standard/SEGA_32X/SEGA32X_Alt-[STD]-[Guest]-[Bezel]-[Night]
segacd:
  shader: Duimon-Mega-Bezel/Presets/Standard/SEGA_CD/SEGACD_Alt-[STD]-[Guest]-[Bezel]-[Night]
saturn:
  shader: Duimon-Mega-Bezel/Presets/Standard/SEGA_Saturn/Saturn-[STD]-[Guest]-[Bezel]-[Night]
# Arcade
arcade:
  shader: Duimon-Mega-Bezel/Presets/Standard/Arcade/Arcade-[STD]-[Guest][CABINET]
cps1:
  shader: Duimon-Mega-Bezel/Presets/Standard/Arcade/Arcade-[STD]-[Guest][CABINET]
cps2:
  shader: Duimon-Mega-Bezel/Presets/Standard/Arcade/Arcade-[STD]-[Guest][CABINET]
cps3:
  shader: Duimon-Mega-Bezel/Presets/Standard/Arcade/Arcade-[STD]-[Guest][CABINET]
neogeo:
  shader: Duimon-Mega-Bezel/Presets/Standard/Neo_Geo_AES/NeoGeo_AES-[STD]-[Guest]-[Bezel]-[Night]
neogeocd:
  shader: Duimon-Mega-Bezel/Presets/Standard/Neo_Geo_CD/NeoGeo_CD-[STD]-[Guest]-[Bezel]-[Night]
mame:
  shader: Duimon-Mega-Bezel/Presets/Standard/MAME/MAME-[STD]-[Guest][CABINET]
fba:
  shader: Duimon-Mega-Bezel/Presets/Standard/FB-Neo/FB-Neo-[STD]-[Guest][CABINET]
fbneo:
  shader: Duimon-Mega-Bezel/Presets/Standard/FB-Neo/FB-Neo-[STD]-[Guest][CABINET]
naomi:
  shader: Duimon-Mega-Bezel/Presets/Standard/Arcade/Arcade-[STD]-[Guest][CABINET]
atomiswave:
  shader: Duimon-Mega-Bezel/Presets/Standard/Arcade/Arcade-[STD]-[Guest][CABINET]
#
3do:
  shader: Duimon-Mega-Bezel/Presets/Standard/Panasonic_3DO/3DO-[STD]-[Guest]-[Bezel]-[Night]
ngp:
  shader: Duimon-Mega-Bezel/Presets/Standard/Neo_Geo_Pocket/NGP-[STD]-[LCD-GRID]-[Night]
ngpc:
  shader: Duimon-Mega-Bezel/Presets/Standard/Neo_Geo_Pocket_Color/NGPC-[STD]-[LCD-GRID]-[Night]
gw:
  shader: 
vectrex:
  shader: 
lynx:
  shader: Duimon-Mega-Bezel/Presets/Standard/Atari_Lynx/Lynx-[STD]-[LCD-GRID]-[Night]
lutro:
  shader: 
wswan:
  shader: Duimon-Mega-Bezel/Presets/Standard/Bandai_WonderSwan/WonderSwan-[STD]-[LCD-GRID]-[Night]
wswanc:
  shader: Duimon-Mega-Bezel/Presets/Standard/Bandai_WonderSwan_Color/WonderSwan_Color-[STD]-[LCD-GRID]-[Night]
pcengine:
  shader: Duimon-Mega-Bezel/Presets/Standard/NEC_PC_Engine/PC_Engine-[STD]-[Guest]-[Bezel]-[Night]
pcenginecd:
  shader: Duimon-Mega-Bezel/Presets/Standard/NEC_PC_Engine_CD/PC_Engine_CD-[STD]-[Guest]-[Bezel]-[Night]
supergrafx:
  shader: Duimon-Mega-Bezel/Presets/Standard/NEC_SuperGrafx/SuperGrafx_Alt-[STD]-[Guest]-[Bezel]-[Night]
atari800:
  shader: Duimon-Mega-Bezel/Presets/Standard/Atari_800/Atari_800-[STD]-[Guest]-[Bezel]-[Night]
atari2600:
  shader: Duimon-Mega-Bezel/Presets/Standard/Atari_2600/Atari_2600-[STD]-[Guest]-[Bezel]-[Night]
atari5200:
  shader: Duimon-Mega-Bezel/Presets/Standard/Atari_5200/Atari_5200-[STD]-[Guest]-[Bezel]-[Night]
atari7800:
  shader: Duimon-Mega-Bezel/Presets/Standard/Atari_7800/Atari_7800-[STD]-[Guest]-[Bezel]-[Night]
prboom:
  shader: Duimon-Mega-Bezel/Presets/Standard/PrBoom/PrBoom-[STD]-[Guest]
psx:
  shader: Duimon-Mega-Bezel/Presets/Standard/SONY_Playstation/Playstation-[STD]-[Guest]-[Bezel]-[Night]
ps2:
  shader: Duimon-Mega-Bezel/Presets/Standard/SONY_Playstation_2/Playstation2-[STD]-[Guest]-[Bezel]-[Night]
psp:
  shader: Duimon-Mega-Bezel/Presets/Standard/Sony_PSP/PSP-[STD]-[Guest]
colecovision:
  shader: Duimon-Mega-Bezel/Presets/Standard/ColecoVision/ColecoVision-[STD]-[Guest]-[Bezel]-[Night]
jaguar:
  shader: Duimon-Mega-Bezel/Presets/Standard/Atari_Jaguar/Jaguar-[STD]-[Guest]-[Bezel]-[Night]
lightgun:
  shader: 
cdi:
  shader: Duimon-Mega-Bezel/Presets/Standard/Philips_CD-i/CD-i-[STD]-[Guest]-[Bezel]-[Night]
# Computers
lutro:
  shader: 
msx:
  shader: Duimon-Mega-Bezel/Presets/Standard/MSX/MSX-[STD]-[Guest]-[Bezel]-[Night]
msx1:
  shader: Duimon-Mega-Bezel/Presets/Standard/MSX/MSX-[STD]-[Guest]-[Bezel]-[Night]
msx2:
  shader: Duimon-Mega-Bezel/Presets/Standard/MSX2/MSX2-[STD]-[Guest]-[Bezel]-[Night]
msx2+:
  shader: Duimon-Mega-Bezel/Presets/Standard/MSX2/MSX2-[STD]-[Guest]-[Bezel]-[Night]
amiga:
  shader: Duimon-Mega-Bezel/Presets/Standard/Amiga_A500_Plus/A500-[STD]-[Guest]-[Bezel]-[Night]
amiga1200:
  shader: Duimon-Mega-Bezel/Presets/Standard/Amiga_A500_Plus/A500-[STD]-[Guest]-[Bezel]-[Night]
amiga500:
  shader: Duimon-Mega-Bezel/Presets/Standard/Amiga_A500_Plus/A500-[STD]-[Guest]-[Bezel]-[Night]
amigacd32:
  shader: Duimon-Mega-Bezel/Presets/Standard/Amiga_A500_Plus/A500-[STD]-[Guest]-[Bezel]-[Night]
amigacdtv:
  shader: Duimon-Mega-Bezel/Presets/Standard/Amiga_A500_Plus/A500-[STD]-[Guest]-[Bezel]-[Night]
c20:
  shader: Duimon-Mega-Bezel/Presets/Standard/Commodore_64C/64C-[STD]-[Guest]-[Bezel]-[Night]
c64:
  shader: Duimon-Mega-Bezel/Presets/Standard/Commodore_64C/64C-[STD]-[Guest]-[Bezel]-[Night]
c128:
  shader: Duimon-Mega-Bezel/Presets/Standard/Commodore_64C/64C-[STD]-[Guest]-[Bezel]-[Night]
cave:
  shader: 
dos:
  shader: Duimon-Mega-Bezel/Presets/Standard/DOSBox/DOSBox-[STD]-[Guest]-[Bezel]-[Night]
amstradcpc:
  shader: Duimon-Mega-Bezel/Presets/Standard/Amstrad_CPC/CPC464-[STD]-[Guest]-[Bezel]-[Night]
atarist:
  shader: Duimon-Mega-Bezel/Presets/Standard/Atari_ST/Atari_ST-[STD]-[Guest]-[Bezel]-[Night]
zx81:
  shader: 
zxspectrum:
  shader: Duimon-Mega-Bezel/Presets/Standard/Sinclair_ZX_Spectrum/ZX_Spectrum-[STD]-[Guest]-[Bezel]-[Night]
odyssey2:
  shader: Duimon-Mega-Bezel/Presets/Standard/Magnavox_Odyssey_2/Odyssey2-[STD]-[Guest]-[Bezel]-[Night]
x68000:
  shader: Duimon-Mega-Bezel/Presets/Standard/Sharp_x68000/x68000-[STD]-[Guest]-[Bezel]-[Night]
o2em:
  shader: Duimon-Mega-Bezel/Presets/Standard/Magnavox_Odyssey_2/Odyssey2-[STD]-[Guest]-[Bezel]-[Night]
scummvm:
  shader: Duimon-Mega-Bezel/Presets/Standard/ScummVM/ScummVM-[STD]-[Guest]-[Bezel]-[Night]
pc98:
  shader: Duimon-Mega-Bezel/Presets/Standard/NEC_PC-9801/PC-9801-[STD]-[Guest]-[Bezel]-[Night]
pcfx:
  shader: Duimon-Mega-Bezel/Presets/Standard/NEC_PC-FX/PC-FX-[STD]-[Guest]-[Bezel]-[Night]
thomson:
  shader: Duimon-Mega-Bezel/Presets/Standard/Thomson_T08/T08-[STD]-[Guest]-[Bezel]-[Night]
pico8:
  shader: Duimon-Mega-Bezel/Presets/Standard/PICO-8/PICO-8-[STD]-[LCD-GRID]-[Night]
x1:
  shader: Duimon-Mega-Bezel/Presets/Standard/Sharp_X1/X1-[STD]-[Guest]-[Bezel]-[Night]