## MEGA BEZEL
default:
  # shader affects retroarch shaders
  shader: crt/crt-geom
  # scanline affect fba2x
  scanline: true
# Reshader  
model2:
  shader: GeomCRT@CRTGeom.fx
model3:
  shader: GeomCRT@CRTGeom.fx
daphne:
  shader: GeomCRT@CRTGeom.fx
solarus:
  shader: GeomCRT@CRTGeom.fx
# Nintendo
snes:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Super_Famicom/Super_Famicom_Alt-[STD]-[Guest-Mini]-[Bezel]
snes-msu:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Super_Famicom/Super_Famicom_Alt-[STD]-[Guest-Mini]-[Bezel]
sgb:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Super_Game_Boy/Super_Famicom_SGB-[STD]-[Guest-Mini]-[Bezel]
nes:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_NES/NES-[STD]-[Guest-Mini]-[Bezel]
n64:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_N64/N64-[STD]-[Guest-Mini]-[Bezel]
satellaview:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Super_Famicom/Super_Famicom_Alt-[STD]-[Guest-Mini]-[Bezel]
sufami:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Super_Famicom/Super_Famicom_Alt-[STD]-[Guest-Mini]-[Bezel]
gba:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_GBA/GBA-[STD]-[LCD-GRID]
gb:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Game_Boy/Gameboy-[STD]-[LCD-GRID]
gbc:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Game_Boy_Color/GBC-[STD]-[LCD-GRID]
nds:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_NDS/NDS-[STD]-[Guest-Mini]
3ds:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_3DS/3DS-[STD]-[Guest-Mini]
fds:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Famicom/Famicom-[STD]-[Guest-Mini]-[Bezel]
virtualboy:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Virtual_Boy/Virtual_Boy-[STD]-[Guest-Mini]
gamecube:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Gamecube/Gamecube-[STD]-[Guest-Mini]-[Bezel]
wii:
  shader: Duimon-Mega-Bezel/Presets/Lite/Nintendo_Wii/Wii_4x3-[Guest-Mini]
# Sega
dreamcast:
  shader: Duimon-Mega-Bezel/Presets/Lite/SEGA_Dreamcast/Dreamcast-[STD]-[Guest-Mini]-[Bezel]
sg1000:
  shader: Duimon-Mega-Bezel/Presets/Lite/SEGA_SG-1000/SG-1000-[STD]-[Guest-Mini]-[Bezel]
mastersystem:
  shader: Duimon-Mega-Bezel/Presets/Lite/SEGA_Master_System/SMS-[STD]-[Guest-Mini]-[Bezel]
megadrive:
  shader: Duimon-Mega-Bezel/Presets/Lite/SEGA_Genesis/Genesis_Alt-[STD]-[Guest-Mini]-[Bezel]
gamegear:
  shader: Duimon-Mega-Bezel/Presets/Lite/SEGA_Game_Gear/Game_Gear-[STD]-[LCD-GRID]
sega32x:
  shader: Duimon-Mega-Bezel/Presets/Lite/SEGA_32X/SEGA32X_Alt-[STD]-[Guest-Mini]-[Bezel]
segacd:
  shader: Duimon-Mega-Bezel/Presets/Lite/SEGA_CD/SEGACD_Alt-[STD]-[Guest-Mini]-[Bezel]
saturn:
  shader: Duimon-Mega-Bezel/Presets/Lite/SEGA_Saturn/Saturn-[STD]-[Guest-Mini]-[Bezel]
# Arcade
arcade:
  shader: Duimon-Mega-Bezel/Presets/Lite/Arcade/Arcade-[STD]-[Guest-Mini][CABINET]
cps1:
  shader: Duimon-Mega-Bezel/Presets/Lite/Arcade/Arcade-[STD]-[Guest-Mini][CABINET]
cps2:
  shader: Duimon-Mega-Bezel/Presets/Lite/Arcade/Arcade-[STD]-[Guest-Mini][CABINET]
cps3:
  shader: Duimon-Mega-Bezel/Presets/Lite/Arcade/Arcade-[STD]-[Guest-Mini][CABINET]
neogeo:
  shader: Duimon-Mega-Bezel/Presets/Lite/Neo_Geo_AES/NeoGeo_AES-[STD]-[Guest-Mini]-[Bezel]
neogeocd:
  shader: Duimon-Mega-Bezel/Presets/Lite/Neo_Geo_CD/NeoGeo_CD-[STD]-[Guest-Mini]-[Bezel]
mame:
  shader: Duimon-Mega-Bezel/Presets/Lite/MAME/MAME-[STD]-[Guest-Mini][CABINET]
fba:
  shader: Duimon-Mega-Bezel/Presets/Lite/FB-Neo/FB-Neo-[STD]-[Guest-Mini][CABINET]
fbneo:
  shader: Duimon-Mega-Bezel/Presets/Lite/FB-Neo/FB-Neo-[STD]-[Guest-Mini][CABINET]
naomi:
  shader: Duimon-Mega-Bezel/Presets/Lite/Arcade/Arcade-[STD]-[Guest-Mini][CABINET]
atomiswave:
  shader: Duimon-Mega-Bezel/Presets/Lite/Arcade/Arcade-[STD]-[Guest-Mini][CABINET]
#
3do:
  shader: Duimon-Mega-Bezel/Presets/Lite/Panasonic_3DO/3DO-[STD]-[Guest-Mini]-[Bezel]
ngp:
  shader: Duimon-Mega-Bezel/Presets/Lite/Neo_Geo_Pocket/NGP-[STD]-[LCD-GRID]
ngpc:
  shader: Duimon-Mega-Bezel/Presets/Lite/Neo_Geo_Pocket_Color/NGPC-[STD]-[LCD-GRID]
gw:
  shader: 
vectrex:
  shader: 
lynx:
  shader: Duimon-Mega-Bezel/Presets/Lite/Atari_Lynx/Lynx-[STD]-[LCD-GRID]
lutro:
  shader: 
wswan:
  shader: Duimon-Mega-Bezel/Presets/Lite/Bandai_WonderSwan/WonderSwan-[STD]-[LCD-GRID]
wswanc:
  shader: Duimon-Mega-Bezel/Presets/Lite/Bandai_WonderSwan_Color/WonderSwan_Color-[STD]-[LCD-GRID]
pcengine:
  shader: Duimon-Mega-Bezel/Presets/Lite/NEC_PC_Engine/PC_Engine-[STD]-[Guest-Mini]-[Bezel]
pcenginecd:
  shader: Duimon-Mega-Bezel/Presets/Lite/NEC_PC_Engine_CD/PC_Engine_CD-[STD]-[Guest-Mini]-[Bezel]
supergrafx:
  shader: Duimon-Mega-Bezel/Presets/Lite/NEC_SuperGrafx/SuperGrafx_Alt-[STD]-[Guest-Mini]-[Bezel]
atari800:
  shader: Duimon-Mega-Bezel/Presets/Lite/Atari_800/Atari_800-[STD]-[Guest-Mini]-[Bezel]
atari2600:
  shader: Duimon-Mega-Bezel/Presets/Lite/Atari_2600/2600-[STD]-[Guest-Mini]-[Bezel]
atari5200:
  shader: Duimon-Mega-Bezel/Presets/Lite/Atari_5200/5200-[STD]-[Guest-Mini]-[Bezel]
atari7800:
  shader: Duimon-Mega-Bezel/Presets/Lite/Atari_7800/7800-[STD]-[Guest-Mini]-[Bezel]
prboom:
  shader: Duimon-Mega-Bezel/Presets/Lite/PrBoom/PrBoom-[STD]-[Guest-Mini]
psx:
  shader: Duimon-Mega-Bezel/Presets/Lite/SONY_Playstation/Playstation-[STD]-[Guest-Mini]-[Bezel]
ps2:
  shader: Duimon-Mega-Bezel/Presets/Lite/SONY_Playstation_2/Playstation2-[STD]-[Guest-Mini]-[Bezel]
psp:
  shader: Duimon-Mega-Bezel/Presets/Lite/Sony_PSP/PSP-[STD]-[Guest-Mini]
colecovision:
  shader: Duimon-Mega-Bezel/Presets/Lite/ColecoVision/ColecoVision-[STD]-[Guest-Mini]-[Bezel]
jaguar:
  shader: Duimon-Mega-Bezel/Presets/Lite/Atari_Jaguar/Jaguar-[STD]-[Guest-Mini]-[Bezel]
lightgun:
  shader: 
cdi:
  shader: Duimon-Mega-Bezel/Presets/Lite/Philips_CD-i/CD-i-[STD]-[Guest-Mini]-[Bezel]
# Computers
lutro:
  shader: 
msx:
  shader: Duimon-Mega-Bezel/Presets/Lite/MSX/MSX-[STD]-[Guest-Mini]-[Bezel]
msx1:
  shader: Duimon-Mega-Bezel/Presets/Lite/MSX/MSX-[STD]-[Guest-Mini]-[Bezel]
msx2:
  shader: Duimon-Mega-Bezel/Presets/Lite/MSX2/MSX2-[STD]-[Guest-Mini]-[Bezel]
msx2+:
  shader: Duimon-Mega-Bezel/Presets/Lite/MSX2/MSX2-[STD]-[Guest-Mini]-[Bezel]
amiga:
  shader: Duimon-Mega-Bezel/Presets/Lite/Amiga_A500_Plus/A500-[STD]-[Guest-Mini]-[Bezel]
amiga1200:
  shader: Duimon-Mega-Bezel/Presets/Lite/Amiga_A500_Plus/A500-[STD]-[Guest-Mini]-[Bezel]
amiga500:
  shader: Duimon-Mega-Bezel/Presets/Lite/Amiga_A500_Plus/A500-[STD]-[Guest-Mini]-[Bezel]
amigacd32:
  shader: Duimon-Mega-Bezel/Presets/Lite/Amiga_A500_Plus/A500-[STD]-[Guest-Mini]-[Bezel]
amigacdtv:
  shader: Duimon-Mega-Bezel/Presets/Lite/Amiga_A500_Plus/A500-[STD]-[Guest-Mini]-[Bezel]
c20:
  shader: Duimon-Mega-Bezel/Presets/Lite/Commodore_64C/64C-[STD]-[Guest-Mini]-[Bezel]
c64:
  shader: Duimon-Mega-Bezel/Presets/Lite/Commodore_64C/64C-[STD]-[Guest-Mini]-[Bezel]
c128:
  shader: Duimon-Mega-Bezel/Presets/Lite/Commodore_64C/64C-[STD]-[Guest-Mini]-[Bezel]
cave:
  shader: 
dos:
  shader: Duimon-Mega-Bezel/Presets/Lite/DOSBox/DOSBox-[STD]-[Guest-Mini]-[Bezel]
amstradcpc:
  shader: Duimon-Mega-Bezel/Presets/Lite/Amstrad_CPC/CPC464-[STD]-[Guest-Mini]-[Bezel]
gx4000:
  shader: Duimon-Mega-Bezel/Presets/Advanced/Amstrad_GX4000/Amstrad_GX4000-[STD]-[Guest-Mini]-[Bezel]  
atarist:
  shader: Duimon-Mega-Bezel/Presets/Lite/Atari_ST/Atari_ST-[STD]-[Guest-Mini]-[Bezel]
zx81:
  shader: 
zxspectrum:
  shader: Duimon-Mega-Bezel/Presets/Lite/Sinclair_ZX_Spectrum/ZX_Spectrum-[STD]-[Guest-Mini]-[Bezel]
odyssey2:
  shader: Duimon-Mega-Bezel/Presets/Lite/Magnavox_Odyssey_2/Odyssey2-[STD]-[Guest-Mini]-[Bezel]
x68000:
  shader: Duimon-Mega-Bezel/Presets/Lite/Sharp_x68000/x68000-[STD]-[Guest-Mini]-[Bezel]
o2em:
  shader: Duimon-Mega-Bezel/Presets/Lite/Magnavox_Odyssey_2/Odyssey2-[STD]-[Guest-Mini]-[Bezel]
scummvm:
  shader: Duimon-Mega-Bezel/Presets/Lite/ScummVM/ScummVM-[STD]-[Guest-Mini]-[Bezel]
pc98:
  shader: Duimon-Mega-Bezel/Presets/Lite/NEC_PC-9801/PC-9801-[STD]-[Guest-Mini]-[Bezel]
pcfx:
  shader: Duimon-Mega-Bezel/Presets/Lite/NEC_PC-FX/PC-FX-[STD]-[Guest-Mini]-[Bezel]
thomson:
  shader: Duimon-Mega-Bezel/Presets/Lite/Thomson_T08/T08-[STD]-[Guest-Mini]-[Bezel]
pico8:
  shader: Duimon-Mega-Bezel/Presets/Lite/PICO-8/PICO-8-[STD]-[LCD-GRID]
x1:
  shader: Duimon-Mega-Bezel/Presets/Lite/Sharp_X1/X1-[STD]-[Guest-Mini]-[Bezel]